# Generated by Django 3.1.5 on 2021-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_auto_20210203_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='banned'),
        ),
    ]
