# Generated by Django 3.1.5 on 2021-02-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'level__lte': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='news.comment'),
        ),
    ]
