# Generated by Django 3.1.5 on 2021-02-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210204_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
