# Generated by Django 3.1.5 on 2021-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
