# Generated by Django 3.1.5 on 2021-02-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210206_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'News Comment', 'verbose_name_plural': 'News Comments'},
        ),
    ]
