# Generated by Django 3.1.5 on 2021-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20210207_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='left',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='right',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
    ]
