# Generated by Django 3.1.5 on 2021-02-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20210207_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='rgt',
            field=models.PositiveIntegerField(db_index=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='comments.comment'),
        ),
    ]
